version: '3.7'

services:
  docs:
    build: .
    image: docs
    container_name: docs
    restart: always
    ports:
      - '127.0.0.1:4000:80'   # use with proxy server (eg. Nginx)
      # - '0.0.0.0:80:3000'     # use without proxy server
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
